### ISSUE TITLE
Doc Bug: Initial Repository Setup For Custom Build · QGroundControl Developer Guide

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgc-dev-guide#103]
multiple typos in "Custom Build Respository" part (including but not limited to title)

Bug Page: [Initial Repository Setup For Custom Build · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/en/custom_build/CreateRepos.html)

**Comment by hamishwillee** [comment]
Closing, because you fixed it. Exactly the right thing to do :-)
