### ISSUE TITLE
compatible Qt and VS versions

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgc-dev-guide#105]
if higher visual studio and Qt versions are supported it should be mentioned in Getting started page. Normally I would think this is not an issue however since Qt 5.12.6 is an archived old version, some errors related to it might go unnoticed (in my case Online installer failed to download related files). 
If anyone uses other version and able to build QGroundControl , feel free to comment

Bug Page: [Getting Started · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/en/getting_started/?q=)

**Comment by DonLakeFlyer** [comment]
> if higher visual studio and Qt versions are supported it should be mentioned

It is not mentioned because it is not supported. As the docs say **only** 5.12.6 is supported.
