### ISSUE TITLE
Doc Bug: Fly View Customization · (outdated)

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgc-dev-guide#106]
As I understand this part is outdated in v4.0.8 ( there are no files named FlyView.qml and FlyViewCustomLayer.qml for instance) 
issue  #88 fixed a similiar thing.

Bug Page: [Fly View Customization · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/en/custom_build/FlyView.html)

**Comment by mnumanuyar** [comment]
[Resource Overrides page](https://dev.qgroundcontrol.com/en/custom_build/ResourceOverride.html) is also outdated.  qgroundcontrol.exclusion and qgcresources.exclusion is no longer in v4.0.8

**Comment by DonLakeFlyer** [comment]
The docs are specific to current master not stable.

**Comment by mnumanuyar** [comment]
oh ok, I was confused because the version number at the top of the [overview page](https://dev.qgroundcontrol.com/en/) was 4.0.8 (now it is 4.0.9) but I guess it is an automatic thing and not specificly related to docs.

**Comment by DonLakeFlyer** [comment]
The QGC docs don't have different versions for Stable and Daily builds. So they are kind of a mix of both depending on what you are looking at. I know not super helpful to understand what is where.
