### ISSUE TITLE
Doc Feature Request: How to generate appimage 

### ISSUE THREAD

**Issue by mnumanuyar** [mavlink/qgc-dev-guide#114]
adding config+=install as described here generates a package folder and a tarball in it. However extracting this tar in another computer and running the executable file did not work.
From the error I got I assume this is because some missing library. As I understand generating appimage is the solution for this problem (qground also puts appimage to relases) .Also probably [this file](https://github.com/mavlink/qgroundcontrol/blob/master/deploy/create_linux_appimage.sh) in qground git generates the appimage. However I couldn't find anywhere how to use it and couldnt figure out myself. If this is the way to generate app image, please add how to use it at the "Building QGC Installation Files" section.
Note: I am new with linux so if I might be missing something obvious please tell
(https://dev.qgroundcontrol.com/master/en/getting_started/index.html)

**Comment by hamishwillee** [comment]
@DonLakeFlyer One for you - essentially add instructions for building AppImage here: https://dev.qgroundcontrol.com/master/en/getting_started/index.html#building-qgc-installation-files

**Comment by DonLakeFlyer** [comment]
This isn't really supported yet. The AppImage build scripts are only meant to run in CI as it stands now. The goal is to move them to work in the regular build system and then you just use CONFIG+=installer and it will be created. But haven't had time to make that work.

**Comment by mnumanuyar** [comment]
Ok, thank you for response. Is it feesible to explain in docs how to set up a similiar CI ? If not, this issue can be closed I think.

**Comment by DonLakeFlyer** [comment]
There isn't anything special about QGC CI. It just uses travis and appveyor. If you understand how those work then you can easily follow what QGC does.
