### ISSUE TITLE
Doc Bug: Using QGC on CentOS · QGroundControl Developer Guide

### ISSUE THREAD

**Issue by DragonOnGit** [mavlink/qgc-dev-guide#115]
There is a translation mistake here in Chinese version
![image](https://user-images.githubusercontent.com/14939159/102750080-29cc1100-43a0-11eb-9ed6-564cf3e788b1.png)
which in the same place in English version
![image](https://user-images.githubusercontent.com/14939159/102750145-48caa300-43a0-11eb-8056-31ab49df6e31.png)
The code above in Chinese version will have got an error reported like:
`no such option: --skip-break-y`

Bug Page: [Using QGC on CentOS · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/master/en/getting_started/CentOS.html)

**Comment by hamishwillee** [comment]
Thank you. I have fixed it in Crowdin. Should appear in the docs in a day or so.
