### ISSUE TITLE
Update build docs for Qt 5.15

### ISSUE THREAD

**Issue by ES-Alexander** [mavlink/qgc-dev-guide#135]
Docs being out of sync with the actual build process is causing support issues. [This forum comment](https://discuss.bluerobotics.com/t/problem-building-qgc-in-visual-studio-using-qt/10751/8) may be a reasonable starting point.

**Comment by ES-Alexander** [comment]
@hamishwillee I believe the Visual Studio and other Windows stuff should be changed to the 2019 versions. @patrickelectric recommended that to me yesterday and it worked successfully. I've just checked again in the Qt Setup and I don't believe an MSVC 2017 version exists (which can also be seen in the relevant screenshot in the forum comment I linked to) :-)

**Comment by hamishwillee** [comment]
Thanks - I just updated the value of Qt. Would you be able to make the required changes. Earliest I would look at it might be late next week.

**Comment by ES-Alexander** [comment]
I'll see if I can get a PR sorted this arvo/tomorrow :-)
