### ISSUE TITLE
Doc Bug: Resources Overrides · QGroundControl Developer Guide

### ISSUE THREAD

**Issue by enetkilifatih** [mavlink/qgc-dev-guide#141]
There is a typo issue at the first sentence.

_... QGC **sourec** code terminology ..._

Bug Page: [Resources Overrides · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/master/en/custom_build/ResourceOverride.html)

**Comment by hamishwillee** [comment]
Thanks. Fixed https://github.com/mavlink/qgc-dev-guide/commit/ff3f28c0e17f99d5cbf74317be8ae93be4b06dcd
