### ISSUE TITLE
Doc Bug: Build using Containers · QGroundControl Developer Guide

### ISSUE THREAD

**Issue by ljustice-riis** [mavlink/qgc-dev-guide#154]
Following the instructions here on a Mac with an M1 chip fails.  Recommending a note about adding the `--platform linux/x86_64` argument when building the docker image.  See: https://stackoverflow.com/questions/68630526/lib64-ld-linux-x86-64-so-2-no-such-file-or-directory-error

Bug Page: [Build using Containers · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/master/en/getting_started/container.html)

**Comment by hamishwillee** [comment]
Thanks - sounds reasonable! What's the error you see? `/lib64/ld-linux-x86-64.so.2: No such file or directory`?

**Comment by ljustice-riis** [comment]
Correct.  Here's the full error I was seeing.

```
> docker run --rm -v ${PWD}:/project/source -v ${PWD}/build:/project/build qgc-linux-docker
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

Rebuilding with `docker build --platform linux/x86_64 --file ./deploy/docker/Dockerfile-build-linux -t qgc-linux-docker .` solved the issue.

**Comment by hamishwillee** [comment]
Thanks. I'll look at adding this tomorrow.
