### ISSUE TITLE
Build fails due to   curl  is not installed on Ubuntu. Please add a hint in point "1" to indicate that

### ISSUE THREAD

**Issue by alanmehio** [mavlink/qgc-dev-guide#159]
The build  when executing make after this step "Build using the "hammer" (or "play") icons:" 
it result with an error  missing header file "#include <airmap/qt/client.h>" as per this  post 
https://discuss.px4.io/t/missing-header-files/22635
The "curl" needs to be installed on the machine since this file "QGCExternalLibs.pri" has a curl call which gets to download the airmap 
inside the libs. 
It would be good to add the following hint in step 1 stating to check the existing of "curl" installed otherwise "curl" has to exist to avoid the error during the make.

**Comment by hamishwillee** [comment]
Airmap is only present on a few platforms right, and optional even on those? Good to mention any dependencies, but this should live next to instructions for installing Airmap.

**Comment by DonLakeFlyer** [comment]
There aren't any instructions for installing airmap. It is supposed to install itself during the build.

**Comment by hamishwillee** [comment]
Thanks @DonLakeFlyer - so should this be a Ununtu dependency as suggested? Or is this optional, or a bug or what?

**Comment by hamishwillee** [comment]
Thanks @alanmehio - sorry for the delay, fixed in #162.

**Comment by alanmehio** [comment]
Hamish,
Great. All the best to you and your team.
// Alan
