### ISSUE TITLE
Doc Bug: Build using Containers · QGroundControl Developer Guide

### ISSUE THREAD

**Issue by kushnayak** [mavlink/qgc-dev-guide#160]
"`./deploy/container`" on the docs should be changed to `./deploy/docker` to match proper directory names

Bug Page: [Build using Containers · QGroundControl Developer Guide](https://dev.qgroundcontrol.com/master/en/getting_started/container.html)

**Comment by hamishwillee** [comment]
Thanks. Fixed in https://github.com/mavlink/qgc-dev-guide/commit/8640975eb284e003b021790edab17a86b533ec7b - should update later today on live server
