### ISSUE TITLE
The build is complete but the icon is not visible

### ISSUE THREAD

**Issue by ukb1** [mavlink/qgc-dev-guide#167]
I compiled with QGC cmake but the icon is not showing

![image](https://user-images.githubusercontent.com/121784535/211567615-4b9e282d-c9bc-4253-a406-3dcd49bf63b2.png)

**Comment by hamishwillee** [comment]
Closing as this is the place for errors in the docs. For support see https://dev.qgroundcontrol.com/master/en/index.html#support
