### ISSUE TITLE
How can I fill the whole screen with QGC?

### ISSUE THREAD

**Issue by ukb1** [mavlink/qgc-dev-guide#168]
I want to fill the entire screen with QGC. Including the windows taskbar section at the bottom. no need to show the close minimize buttons on the top, as if f11 is pressed.
mainRootWindow.qml 

`
ApplicationWindow {
    id:             mainWindow
//    minimumWidth:   ScreenTools.isMobile ? Screen.width  : Math.min(ScreenTools.defaultFontPixelWidth * 100, Screen.width)
//    minimumHeight:  ScreenTools.isMobile ? Screen.height : Math.min(ScreenTools.defaultFontPixelWidth * 50, Screen.height)
    visible: true
    visibility: Window.FullScreen
//    visibility: mainWindow.FullScreen
    Component.onCompleted: {

        if (!ScreenTools.isMobile || Screen.height / ScreenTools.realPixelDensity < 120 ) {
             console.log("APP: true")
            mainWindow.showFullScreen()

        } else {
            console.log("APP: false")
//            width   = ScreenTools.isMobile ? Screen.width  : Math.min(250 * Screen.pixelDensity, Screen.width)
//            height  = ScreenTools.isMobile ? Screen.height : Math.min(150 * Screen.pixelDensity, Screen.height)
            mainWindow.fullScreen()
        }

        firstRunPromptManager.nextPrompt()
    }
`
I added main mainWindow.fullScreen() to the else part of this code, but still no change

**Comment by hamishwillee** [comment]
I have no idea. YOur best bet is to ask on the discussion forums. This is for issues with the docs.
