### ISSUE TITLE
Add License page

### ISSUE THREAD

**Issue by hamishwillee** [mavlink/qgc-dev-guide#26]
Create page with link to all licences associated with QGC project:
- The source code of QGroundControl is licensed under the [GPLv3](https://github.com/mavlink/qgroundcontrol/blob/master/license.txt)  (or later)
- Artwork/images are licensed under CC by SA
- User Guide and Dev Guide- CC BY 4.0 ?

Confirm version for images/artwork. Confirm version licence for docs.

Propose this lives in dev guide under code submission, and includes a note that anything submitted must also comply with X license.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Even if we don't have this doc, we do need to add license files for the user guide and dev guide.  Propose we use CC BY 4.0 like PX4 and DroneCore guides?

**Comment by LorenzMeier** [comment]
@hamishwillee QGC is dual-licensed: GPLv3 or Apache 2

**Comment by LorenzMeier** [comment]
https://github.com/mavlink/qgroundcontrol/blob/master/COPYING.md

**Comment by LorenzMeier** [comment]
@hamishwillee Docs should be CC-BY as well like in the other cases.

**Comment by hamishwillee** [comment]
Thanks @LorenzMeier . Closed by #27. New page [here](https://dev.qgroundcontrol.com/en/contribute/licences.html)
