### ISSUE TITLE
compile qgroundcontrol in windows 10

### ISSUE THREAD

**Issue by hamid5026** [mavlink/qgc-dev-guide#34]
Hi 
I git qgroundcontrol but have many problem with its compile. if I use MSVC2015 32 bit I get this:
":-1: error: Unsupported Windows toolchain, only Visual Studio 2010, 2012, and 2013 are supported"
 and If I use MSVC2013 64bit I get a lot of error like it :
"...\QGCMapEngineData.h:39: error: C2065: 'UINT64_MAX' : undeclared identifier"
I have an Asus laptop 64 bit (K556U) with Windows 10. 
QT 5.9.3 and VS2013, VS2015 and VS 2017 is installed.
please help me. what should I do. I didn't find any clear step by step procedure for compiling this software in the net. I did it 2-3 years age with VS2010 and QT on Windows 7 and a 32 bit system. but at the moment I didn't have that system and software.
Thanks in advances.
Hamid Moghadspour.

**Comment by hamishwillee** [comment]
Hi Hamid, this section is really for errors in docs. Suggest you raise this discussion in http://discuss.px4.io/c/qgroundcontrol/qgroundcontrol-developers

There is some building guidance in https://github.com/mavlink/qgroundcontrol/#qgroundcontrol-ground-control-station
