### ISSUE TITLE
Doc Bug: Getting Started · QGroundControl Developers Guide

### ISSUE THREAD

**Issue by Desync-o-tron** [mavlink/qgc-dev-guide#59]
"Ubuntu: Desktop Qt 5.11.0 GCC bit"

^ this line is incomplete.. what bit??

Bug Page: [Getting Started · QGroundControl Developers Guide](https://dev.qgroundcontrol.com/en/getting_started/)

**Comment by hamishwillee** [comment]
Thanks. Fixed
