### ISSUE TITLE
Doc Bug: Plan View · QGroundControl Developers Guide

### ISSUE THREAD

**Issue by simkslv** [mavlink/qgc-dev-guide#62]
DESCRIBE PROBLEM WITH DOCS HERE

I cannot find MissionEditor.qml that is mentioned as Top level QML code of Plan View  in the project folders. 

Bug Page: [Plan View · QGroundControl Developers Guide](https://dev.qgroundcontrol.com/en/views/plan.html)

**Comment by hamishwillee** [comment]
@DonLakeFlyer I guess this got changed to [PlanView.qml](https://github.com/mavlink/qgroundcontrol/blob/master/src/PlanView/PlanView.qml)?

While we're here, are the other 2 items still accurate? https://dev.qgroundcontrol.com/en/views/plan.html

**Comment by DonLakeFlyer** [comment]
> I guess this got changed to [PlanView.qml](https://github.com/mavlink/qgroundcontrol/blob/master/src/PlanView/PlanView.qml)?

correct

> While we're here, are the other 2 items still accurate?

yes

**Comment by hamishwillee** [comment]
@simkslv There you have it. This was fixed in https://github.com/mavlink/qgc-dev-guide/commit/1f6adc37b204003e7a78fbb15b910854faf1d680
