### ISSUE TITLE
Doc Bug: Getting Started · QGroundControl Developers Guide

### ISSUE THREAD

**Issue by pattee** [mavlink/qgc-dev-guide#64]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [Getting Started · QGroundControl Developers Guide](https://dev.qgroundcontrol.com/en/getting_started/)

Typo: 

Under 'To install Qt:' in number 2. it lists for Windows 'MCVC 2015 32 bit'.

I believe that should be MSVC not MCVC.

**Comment by hamishwillee** [comment]
Thanks very much @pattee - Fixed. FYI, you can do these sorts of fixes yourself if you want as a PR by pressing this button instead of the bug button:
![image](https://user-images.githubusercontent.com/5368500/58669975-df7bdd00-8380-11e9-992e-bb3b7f688538.png)
