### ISSUE TITLE
compile qgroundcontrol

### ISSUE THREAD

**Issue by HakkiGoktas** [mavlink/qgc-dev-guide#69]
Hi
I git qgroundcontrol but have problem with its compile. I get this:
"error: Unsupported Windows toolchain, only Visual Studio 2010, 2012, and 2013 are supported"
QT 5.13.0 and VS2013, VS2015 is installed.
Please help me. What should I do? I didn't find any clear step by step procedure for compiling this software in the net.
Thanks in advances.

**Comment by HakkiGoktas** [comment]
Now I get this error:
"Unknown module(s) in QT: charts"

**Comment by DonLakeFlyer** [comment]
Go here: https://github.com/mavlink/qgroundcontrol, go to the bottom of the page and read
