### ISSUE TITLE
Doc Bug: Getting Started · QGroundControl Developers Guide

### ISSUE THREAD

**Issue by Rasmunis** [mavlink/qgc-dev-guide#76]
The Qt-version in the docs on building for Android did not work for me. I had to upgrade to 5.12.4.

Bug Page: [Getting Started · QGroundControl Developers Guide](https://dev.qgroundcontrol.com/en/getting_started/#building-using-qt-creator)

**Comment by olliw42** [comment]
I have not tried 5.12.4 but also have found that the docs cannot be correct.

It says to install "MSVC 2015 32 bit" and Qt 5.12.5, and for Qt it says to select "MSVC 2015 32 bit". However Qt 5.12.5 doe NOT offer an option "MSVC 2015 32 bit" but only these options:

![qgc-msvc](https://user-images.githubusercontent.com/6089567/72208905-eaffbc80-34a8-11ea-9e3b-f3a1730b5f9a.jpg)

When I run QtCreator with my existing install, which worked until a month ago or so, it shows several complains, among it the complain that it wants to see MVSC 2017.

From that I would think that the docs should say that one should install MSVC 2017 and that the selection in Qt should be accordingly (32bit or 64bit?) but that's just a guess.

I would very much appreciate if the docs could be updated to what is needed to work successfully with latest master.

THX!!!

Cheers, Olli

**Comment by hamishwillee** [comment]
Hi @DonLakeFlyer ,

So the line in question is probably "*Windows: Desktop Qt 5.12.5 MSVC2015 32bit*". Did you update to 2017 in the last round?

**Comment by DonLakeFlyer** [comment]
Windows now uses VS 2017 64 bit. I can't remember what that is named in the Qt downloader.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Thanks. I downloaded *Visual Studio Community 2017 (version 15.9)*. There are a hell of a lot of possible components, and they don't match previous version. Can you confirm how you select the "right ones".

E.g. I could select a Workload or individual packages as shown below:

![image](https://user-images.githubusercontent.com/5368500/72585640-eb81d280-3942-11ea-88a2-432b2e2d0dee.png)

![image](https://user-images.githubusercontent.com/5368500/72585701-15d39000-3943-11ea-8c50-2fe97adefee3.png)

**Comment by DonLakeFlyer** [comment]
I think would you selected is correct.Can't quite remember how I did it.
