### ISSUE TITLE
Doc Bug: Getting Started · QGroundControl Developers Guide

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgc-dev-guide#79]
Apparently QGC master requires Qt 5.12.5, not 5.11.3. Can we keep this information in a place where it is maintained and in sync? Maybe in the README of the source tree?
@DonLakeFlyer 

Bug Page: [Getting Started · QGroundControl Developers Guide](https://dev.qgroundcontrol.com/en/getting_started/#native-builds)

**Comment by hamishwillee** [comment]
@bkueng That page is exactly where it is supposed to be maintained and kept in sync - doing so in the readme would be duplication. As to why it is out of date, I don't know. @DonLakeFlyer is Qt 5.12.5 correct for all platforms?

**Comment by DonLakeFlyer** [comment]
> Apparently QGC master requires Qt 5.12.5, not 5.11.3.

That is correct.

**Comment by DonLakeFlyer** [comment]
> As to why it is out of date, I don't know.

It's out of date because I tend to be the only one who deals with ongoing maintenance burden of QGC. And I'm dealing with a long list of things to deal with and not a lot of time to get them done.  I just finished switching things over a few weeks ago.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mavlink/qgc-dev-guide/commit/d0c0e13612d1c5c43823e0074e75ddba1ea6499b

No worries @DonLakeFlyer. I just don't want to change our ways of working for this.

**Comment by DonLakeFlyer** [comment]
I don't really see a better way to do this at the moment without requiring updates in multiple places. I'll try to think about it a little when I get back home.

**Comment by bkueng** [comment]
That's fine with me, I was just thinking something closer to the source would ensure it's more up to date.
Thanks.
