### ISSUE TITLE
error: C2259: ‘CustomVideoReceiver’: cannot instantiate abstract class

### ISSUE THREAD

**Issue by NectroX** [mavlink/qgc-dev-guide#84]
Hi,

i am trying to compile the custom-example build using qt 5.12.6 but i am getting this error..
error: C2259: ‘CustomVideoReceiver’: cannot instantiate abstract class
![class](https://user-images.githubusercontent.com/60704518/77662892-5db40a80-6fb7-11ea-8db2-caedc44127cb.png)

**Comment by DonLakeFlyer** [comment]
Issues here are for problems with the developer guide documentation. QGC source is here: https://github.com/mavlink/qgroundcontrol
