### ISSUE TITLE
Documentation for non-existing custom build update script

### ISSUE THREAD

**Issue by mortenfyhn** [mavlink/qgc-dev-guide#88]
Not sure if this is considered a bug here or in QGroundControl itself.

On https://dev.qgroundcontrol.com/en/custom_build/upstream_merge.html#upstream-merge there is a mention of a script `updateqrc.py` (maybe a typo of `updateqgc.py`). The way I understand the documentation, this script should be in the `custom` dir, at least when you have a custom build set up, which really means it should be in `custom-example` in the upstream repo. But I cannot find it there or anywhere else. Does it exist?

**Comment by DonLakeFlyer** [comment]
Hmm, I'll take a look. Thanks for the report.

**Comment by DonLakeFlyer** [comment]
This has all been reworked. The example itself including the docs.

**Comment by mortenfyhn** [comment]
That's superb!
