### ISSUE TITLE
Terrain Following in Survey Mission

### ISSUE THREAD

**Issue by chris89116** [mavlink/qgc-dev-guide#89]
Is it possible to fly a survey mission while using an on-board laser rangefinder to follow terrain ?
My mission requires flight at low altitude with tight altitude compliance over rolling terrain. I have experimented using the DEM terrain height but it is just not accurate enough, even using 1 meter DEM data.

[https://discuss.px4.io/t/terrain-following-in-survey-mission/11681](url)

**Comment by DonLakeFlyer** [comment]
@chris89116 Can you move this to here: https://github.com/mavlink/qgroundcontrol

**Comment by chris89116** [comment]
Ok it's done
